import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import {
  Box,
  Button,
  FormControl,
  FormLabel,
  Heading,
  Input,
  Stack,
  useEditable,
} from "@chakra-ui/react";
import { useUser } from "../contexts/UserContext";
import { useRouter } from "next/router";

export default function Home() {
  const [email, setEmail] = useState("");
  const [nome, setNome] = useState("");
  const [password, setPassword] = useState("");

  const router = useRouter();
  const { setUser } = useUser();

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!email && !password && !nome) {
      return;
    } else {
      setUser({
        name: nome,
        email,
      });
      router.push("/financeiro/telaFinanceiro");
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Box
          w={"100%"}
          display="flex"
          alignItems="center"
          justifyContent="center"
          bg={"containerPrimary"}
          p={4}
        >
          <Box
            bg="blue.500"
            p={6}
            rounded="md"
            shadow="md"
            width={{ base: "100%", sm: "400px" }}
          >
            <Heading as="h2" mb={6} textAlign="center">
              Acesso
            </Heading>
            <form onSubmit={handleSubmit}>
              <Stack spacing={4}>
                <FormControl id="nome">
                  <FormLabel>Nome</FormLabel>
                  <Input
                    type="nome"
                    value={nome}
                    onChange={(e) => setNome(e.target.value)}
                    placeholder="Digite seu nome"
                    required
                  />
                </FormControl>

                {/* Campo de email */}
                <FormControl id="email">
                  <FormLabel>Email</FormLabel>
                  <Input
                    type="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    placeholder="Digite seu email"
                    required
                  />
                </FormControl>

                {/* Campo de senha */}
                <FormControl id="password">
                  <FormLabel>Senha</FormLabel>
                  <Input
                    type="password"
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    placeholder="Digite sua senha"
                    required
                  />
                </FormControl>

                {/* Botão de login */}
                <Button type="submit" colorScheme="blue" size="lg" width="full">
                  Entrar
                </Button>
              </Stack>
            </form>
          </Box>
        </Box>
      </main>
    </>
  );
}
